### ISSUE TITLE
pretrained model to generate results in the paper

### ISSUE THREAD

**Issue by mj735** [haomo-ai/OverlapTransformer#6]
Hello, thanks for the great work!

I download your pretrained model on kitti, generate depth data using gen_depth_data.py, and run 

python test_kitti00_prepare.py
python test_kitti00_topN.py

but I get 0.883 for Top1 and 0.950 for Top1%, which are good enough but have a little gap to the 0.906 and 0.964 in the paper.

Could you please give me some suggestions to reproduce your results? Thanks!

**Comment by BIT-MJY** [comment]
Hello @mj735 ,

Thanks for using our code!

Have you used the gen_depth_data.py provided in this repo? Or Have you changed it?

I think you should check the relevant setup carefully. The following screenshot of the topN recalls from our experiment is a reference:

![2022-08-01 08-23-41 的屏幕截图](https://user-images.githubusercontent.com/56945855/182051867-cbebf8ac-6ed4-4252-88ec-0dabfcacc391.png)

If you still cannot get the results, I have some advise for improvement:
* increase the range in the `range_projection` function, such as 80 m.
* use .npy instead of .png.
* continue fine-tuning if necessary.

**Comment by mj735** [comment]
Thanks for your reply. I will try it. 
Another question is that in the paper you said seq 03-10 are used for training. But in the config file there is no seq 10, only 03-09 (https://github.com/haomo-ai/OverlapTransformer/blob/85cbc1c3970c8339f91daccc7ac48875d3f5f167/config/config.yml#L19). Is it a bug or are there any reasons?

**Comment by BIT-MJY** [comment]
It's a config param. You can change it according to my paper :)
