### ISSUE TITLE
Is there a search space for evaluation on Haomo?

### ISSUE THREAD

**Issue by lqf211** [haomo-ai/OverlapTransformer#7]
Hi authors,

Really nice work!

I have generated the results on KITTI 00 closed to the ones in your paper, but I want to know why there is no search space in the evaluation on Haomo dataset?

**Comment by BIT-MJY** [comment]
Hi @lqf211,

Thanks for using our code!

Actually, we don't use any search space for retrieval while using either loop closure detection metrics or place recognition metrics. It's just used for better visualization in this repo. OverlapTransformer is a place recognition method instead of a loop closure detection method, so using a search space is not reasonable.

**Comment by lqf211** [comment]
I found there is no search space while evaluating with either loop closure metric or place recognition metric. Thanks for your reply!
